### ISSUE TITLE
Module file was created by an older version of the compiler

### ISSUE THREAD

**Issue by elgs** [auth0/JWTDecode.swift#16]
I built this lib using carthage. My Cartfile look like this:

`github "auth0/JWTDecode.swift"`

When I include `import JWTDecode` in my code, it shows the following error message:

```
Module file was created by an older version of the compiler; rebuild 'JWTDecode' and try again: /Users/elgs/Dev/iOS/LoginTest/Carthage/Build/iOS/JWTDecode.framework/Modules/JWTDecode.swiftmodule/x86_64.swiftmodule
```

**Comment by hzalaz** [comment]
@elgs that's because it was compiled with an older version of Xcode and you are using a newer version. This is because swift provides no ABI compatibility so you will get this error frequently unless we replace all binaries in releases whenever a new Xcode version is out. I'd recommend running carthage with `--no-use-binaries` to avoid using any precompiled framework and compile them in your local machine instead.

We'll probably stop uploading the precompiled framework so carthage can built it directly from source.

**Comment by elgs** [comment]
Thanks. @hzalaz

**Comment by elgs** [comment]
It doesn't matter if you keep the precompiled framework or not if you put the `--no-use-binaries` in the `README.md`. That would be very helpful.
