### ISSUE TITLE
Can we create a JWT encoded toke in our iOS app and embed it in QR code ?

### ISSUE THREAD

**Issue by subinrevi** [auth0/JWTDecode.swift#4]

**Comment by hzalaz** [comment]
@subinrevi this library is only for decoding the JWT payload (and also checking if its expired). 
You can use https://github.com/kylef/JSONWebToken.swift to generate a signed token. 
It's been a while since I've used a lib to generate a QR Code but this was my library of choice https://github.com/TheLevelUp/ZXingObjC

**Comment by subinrevi** [comment]
Hi, Thanks for your reply. Is there any Objective C implementation for generating JSON Web token ?

**Comment by hzalaz** [comment]
I saw this library https://github.com/yourkarma/JWT but never really used it, I'd suggest using the one in my previous commit, at least build a Objc wrapper around it.
